[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Thomas ten Cate <ttencate@gmail.com>"]
edition = "2018"

[dependencies]
aoc = { "path" = "aoc" }
regex = "1"

[profile.release]
# Enable debug information in release builds.
debug = true
