[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Thomas ten Cate <ttencate@gmail.com>"]
edition = "2018"

[dependencies]
aoc = { "path" = "aoc" }
lazy_static = "1.4.0"
multiset = "0.0.5"
regex = "1.4.2"

[profile.release]
# Enable debug information in release builds.
debug = true
